---
  model_name: after-stat-tests
  model_directory: models # Be aware of the location for serving
  data_dir: data/training # Trading sessions are expected as individual files

  # General config
  #! close & volume headers are required; have to match the constants in `lib/constants.py` 
  # Not listed headers will be dropped _after_ preprocessing
  data_headers:
    - progress
    - open
    - high
    - low
    - close
    - volume
  tick_size: 0.25 # Currently not in use
  tick_value: 12.50 # Represents price per contract
  initial_balance: 10000.00
  
  # Hyperparameter
  episodes: 75
  batch_size: 512
  sequence_length: 15
  action_space:
    threshold: 0.3 # 0.00 - 1; 1 -> no action
    trade_limit: 10 # Limit to trade at once
  agent:
    update_frequency: 5 # Target network
    gamma: 0.95
    epsilon: 1.0
    epsilon_final: 0.02
    epsilon_decay: 0.995
    learning_rate: 0.16
  reward_factors:
    session_total: 2
    intrinsic: 1