---
  model_name: prototype-V1
  model_directory: models

  # Trading sessions are expected as individual files
  training_data: data/training
  validation_data: data/validation
  test_data: data/test

  # General config
  #! Close & Volume headers are required; not listed headers will be dropped _after_ preprocessing
  data_headers:
    - Progress
    - Open
    - High
    - Low
    - Close
    - CloseNorm
    - Volume
  tick_size: 0.25 # Currently not in use
  tick_value: 12.50 # Represents price per contract
  initial_balance: 10000.00
  
  # Hyperparameter
  episodes: 50
  batch_size: 512
  sequence_length: 10
  action_space:
    threshold: 0.2 # 0.00 - 1; 1 -> no action
    trade_limit: 75 # Limit to trade at once
  agent:
    update_frequency: 5 # Target network
    memory_size: 350000
    gamma: 0.95
    epsilon: 1.0
    epsilon_final: 0.01
    epsilon_decay: 0.999
    learning_rate: 0.16
  reward_factors:
    session_total: 2
    intrinsic: 1
    hindsight: 0.5