---
  model_name: v1-prototype
  model_directory: models

  # Trading sessions are expected as individual files
  training_data: data/training
  validation_data: data/validation
  test_data: data/test

  # Preprocessing
  source_data: data/source.scv
  session_begin_marker: '18:00:00'
  session_end_marker: '16:59:00'
  marker_column: DateTime
  total_set: 1 # How much of the total data to use
  training_set: 0.7 # Cross training-validation
  validation_set: 0.15
  test_set: 0.15 # Always latest data

  # General config
  #! Close & Volume headers are required; not listed headers will be dropped _after_ preprocessing
  data_headers:
    - Progress
    - Open
    - High
    - Low
    - Close
    - Volume
  tick_size: 0.25 # Currently not in use
  tick_value: 12.50 # Represents price per contract
  initial_balance: 10000.00
  
  # Hyperparameter
  episodes: 100
  batch_size: 4
  sequence_length: 5
  action_space:
    threshold: 0.2 # 0.00 - 1; 1 -> no action
    trade_limit: 500 # Limit to trade at once
  agent:
    update_frequency: 5 # Target network
    memory_size: 2000
    gamma: 0.95
    epsilon: 1.0
    epsilon_final: 0.01
    epsilon_decay: 0.995
  reward_factors:
    session_total: 1.5
    intrinsic: 0.75
    hindsight: 0.5