version: '3'
services:
  tensorflow-serve:
    image: tensorflow/serving:latest-gpu
    volumes:
      - ./models/1:/models/1
    command: --model_base_path=/models --rest_api_port=8501 --model_name=model
    networks:
      - trading

  python-server:
    build:
      dockerfile: ./server/Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - tensorflow-serve
    networks:
      - trading

networks:
  trading: