---
  model_name: metrics-no-HER
  model_directory: models # Be aware of the location for serving
  data_training: data/training # Trading sessions are expected as individual files
  data_validation: data/validation
  validation_dir: data # The foldername where validation summaries are saved
  log_dir: logs

  # General config
  #! close & volume headers are required; have to match the constants in `lib/constants.py` 
  # Not listed headers will be dropped _after_ preprocessing
  data_headers:
    - progress
    - open
    - high
    - low
    - close
    - volume
  initial_balance: 10000.00
  
  # Hyperparameter
  episodes: 100
  batch_size: 512
  sequence_length: 15
  agent:
    update_frequency: 5 # Target network
    gamma: 0.95
    epsilon: 1.0
    epsilon_final: 0.02
    epsilon_decay: 0.995
    learning_rate: 0.16